### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/CoSimIO#165]
small issue to document things we discussed in meetings

@pooyan-dadvand

**Comment by philbucher** [comment]
**Meeting 14.04.2021**

- we agreed to start with the MPI testing environment and to make it work in the CI
- also we should check if we can directly use the `DataCommunicator` from Kratos as we will need those capabilities too
- Meanwhile I am working on the SubComm things in Kratos, they are almost all in master
- also I am splitting the MPI-things in the MappingApp into a separate binary (same as is done e.g. in the FluidDynApp)

**Comment by philbucher** [comment]
Preparation for next meeting:
- Using _CoSiImIO_ in the same program but from different compilation units/different libs (e.g. from KratosCore and StructuralMechanics). I am currently not sure if it works, esp since Kratos has quite some trouble with `static` at the moment. This is the potentially problematic line:
    https://github.com/KratosMultiphysics/CoSimIO/blob/401f53ee318ee8834ff6a3a2a09c0774972b1f79/co_sim_io/impl/co_sim_io_impl.hpp#L33
    I haven't done much research yet, so not sure abt the details. Here are some thoughts though:
    - C++17 can have static inline for variables, maybe that could help
    - maybe using `extern` for all but one compilation unit where the CoSimIO is included could work
    Note the C and Python should not have this problem as there the `static` map is in a lib. But we should discuss it to be sure
-  How to properly test this situation?
- **MPI**:
    - #172 adds the framework for MPI tests in C++
    - How should the interface look like for MPI? I would pass a `MPI_Comm` somehow. But how to do it in a way such that we don't have the `#ifdef USING_MPI` everywhere?

**Comment by pooyan-dadvand** [comment]
It is definitely a problem.... 

I think we may give up to be header-only but let's make research before.

**Comment by philbucher** [comment]
**26.04.2021**
- Discussion whether or not to drop header-only. Reasons for dropping it are:
    - the registration (see above) when including from different dlls
    - the MPI extension, having it header only would probably require quite some `#ifdef USING_MPI`. If we have it not header only then we can have a separate extension (like e.g. the `KratosMPICore`
- I will set up tests when including from different dlls in the CoSimIO testing framework. => also when dlls are compiled as shared/static libs. Note to test also different configurations/hierarchies of dependencies (A.so -> B.so / A.so -> B.so -> C.so / B.so -> A.so <- C.so)
- MPI: If possible keep the same interface for serial and MPI and use the `Settings` to distinguish btw serial/MPI
- Prefix all of the CoSimIO cmake vars with `CO_SIM_IO_` to avoid conflicts (probably some need to be made backward compatible)

@pooyan-dadvand please add if I forgot sth

**Comment by pooyan-dadvand** [comment]
Adding that we also reviewed the status of the development

**Comment by philbucher** [comment]
@pooyan-dadvand I think I found out how pybind does the registration across modules. If I understand they use python to create a unique storage:
https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/internals.h#L255-L312

**Comment by philbucher** [comment]
**Meeting 03.05.2021**
- updated status of developments
- discussing MPI interface
    - We agreed to create an MPI-Extension header (that gets included if `CO_SIM_IO_USE_MPI` is defined) so that we don't have to leak mpi-includes into the serial part
    - Advantage is that this way we can cleanly separate the parts that include MPI from that parts that don't => Very useful when separate binaries exist! (think Core/MPICore)
    - This also means to create a separate `Connect`-fct: `ConnectMPI` which in addition to the serial version accepts an `MPI_Comm` to be used by the CoSimIO
    - We also said that MPI must be initialized before calling `ConnectMPI`, otherwise we throw an error => CoSimIO should NOT initialize MPI, this must be done by the host!
- reviewed PR related to MPI in CI
- MPI C++ CI is done, next step is to do the same for C & Python and add some dummy tests

**Comment by philbucher** [comment]
Preparation for next meeting:
- https://github.com/KratosMultiphysics/Kratos/pull/8709
- https://github.com/KratosMultiphysics/CoSimIO/pull/179
    - esp we have to link everything to MPI when using it, even the serial test, which I don't like but not sure if we can avoid it
    - I like that the MPI is completely separated :)
- https://github.com/KratosMultiphysics/CoSimIO/pull/180 => not really sth to discuss, seems to work well :) Probably once we add more tests we will see how well it works
- Python MPI Interface: 
    - Have our own small module for init and finalization of MPI OR use mpi4py
    - pass the `MPI_Comm` from Python will be interesting to solve => we should know what the using applications do!
    - Probably useful to get the Comm from mpi4py => https://stackoverflow.com/questions/52657173/sharing-an-mpi-communicator-using-pybind11

**Comment by philbucher** [comment]
**Meeting 07.05.2021**
- MPI Interfaces (#179) were discussed and agreed upon
- Passing the `MPI_Comm` in Python is not yet clear, will be seen as we go along in the implementation
- support for Penta elements for mapping would be good! However this will require modifications in Kratos..

**Comment by philbucher** [comment]
Preparation for next meeting:
- #184 
- https://github.com/KratosMultiphysics/Kratos/pull/8709
- Storage in `ModelPart`
- #160 => directly use serializer from Kratos?
- #186
- #182 is ready

**Comment by philbucher** [comment]
for async communication:
three options:
- sync (default)
- async_buffered: copy buffer to own data structure so that user can directly reuse the buffer
- async_unbuffered: requires wait. Most efficient but more difficult to use

~~~C++
CoSimIO::Info export_settings;
CoSimIO::Info export_info = CoSimIO::ExportData(export_settings, some_data);


CoSimIO::Info wait_info = CoSimIO::Wait(export_info);

CoSimIO::Info wait_all_info = CoSimIO::WaitAll();
~~~

Import to be sync for now. Async import only useful when doing stuff in the middle

**Comment by philbucher** [comment]
Serialization:
Port Serializer from Kratos and always serialize things for data exchange => also means to drop vtk for FileComm

**Comment by philbucher** [comment]
Could a raw array be directly serialized?
=> see the serialization in the DataContainer for RawMemory

**Comment by philbucher** [comment]
**for Meeting 26.07.2021:**
- [ ] https://github.com/KratosMultiphysics/Kratos/pull/8976
- [ ] https://github.com/KratosMultiphysics/Kratos/pull/8979
- [ ] #241: for remote controlled CoSim to pass settings and other metadata
- [ ] example of remote controlled CoSim in Kratos
- [ ] #233 (TODO: port some tests)
- [ ] #231
- [ ] #237
- [ ] #234
- [ ] Using `DataCommunicator` in MPI-Connect

**Comment by philbucher** [comment]
for next meeting:
- race condition issues in Win: #253 & #254
- MPI: #251
-  #250 => now proper checking can be done if settings are correct
