### ISSUE TITLE
Error with SIGSTKSZ on newer systems

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/CoSimIO#342]
Error with SIGSTKSZ on newer systems on Ubuntu 22.

- System: Ubuntu 22.04.1 LTS 
- Kernel: 5.15.0-46.generic
- Compiler: g++/gcc 11.2.0

Happen here:
[`static char             altStackMem[4 * SIGSTKSZ];`](https://github.com/KratosMultiphysics/CoSimIO/blob/5a40adeca4a3cf41a8f753b5c27ea480ca996660/external_libraries/doctest/doctest.h#L4299)

The message:
```
/home/guille/Repositories/CoSimIO/external_libraries/doctest/doctest.h:4299:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4299 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
gmake[2]: *** [tests/CMakeFiles/co_sim_io_tests.dir/build.make:90: tests/CMakeFiles/co_sim_io_tests.dir/co_sim_io/cpp/main_test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:958: tests/CMakeFiles/co_sim_io_tests.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 35%] Linking CXX executable connect_disconnect_b_cpp_test
[ 35%] Built target connect_disconnect_b_cpp_test
gmake: *** [Makefile:146: all] Error 2
```

A solution provided by hard-coding, something like this: `static char altStackMem[4 * 8192];`

@mtnzguillermo could be of your interest

**Comment by philbucher** [comment]
should be fixed by updating doctest

afaik @sunethwarna wanted to do this

in the meantime you can disable the tests with `CO_SIM_IO_BUILD_TESTING`

**Comment by sunethwarna** [comment]
The PR is #343 :)

**Comment by philbucher** [comment]
Closing, should be fixed
