### ISSUE TITLE
[Serialization] Error of communication in serialization (coupling two non-Kratos sides)

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/CoSimIO#347]
We are trying to couple two non Kratos applications, but using Kratos CoSimulationApplication as orchestrator, and we are getting the folllowing error during the Serialization process:

~~~sh
CoSimIO: Exporting Data "temp" ... 
CoSimIO: Finished exporting Data temp" 
CoSimIO: Importing Data "heat" ... 
CoSimIO: Finished importing Data heat" 
data Collected size 78528 
CoSimIO: Importing Info "control_signal" ... 
terminate called after throwing an instance of 'CoSimIO::Internals::Exception'
what(): Error: basic_string::_M_replace_aux
in 1. ./co_sim_io/sources/info.cpp : 54 : void CoSimIO::Info::load(CoSimIO::Internals::Serializer&) 
2. ./co_sim_io/includes/communication/communication.hpp : 277 : CoSimIO::Info CoSimIO::Internals::Communication::ReceiveObjectWithStreamSerializer(const CoSimIO::Info&, TObjectType&) [with TObjectType = CoSimIO::Info]
3. ./co_sim_io/sources/communication/communication.cpp : 180 : virtual CoSimIO::Info CoSimIO::Internals::Communication::ImportInfoImpl(const CoSimIO::Info&)
~~~

A priori the error message "basic_string::_M_replace_aux"  occurs when there is an issue with the "replace" function of the "std::basic_string" class. The specific error "basic_string::_M_replace_aux" suggests that there is an issue with the internal implementation of the "replace" function. This can happen if you provide incorrect arguments or if there is a problem with memory allocation. I don't know this could be something from our side when implementing the wrapper. Any idea or suggestion?

I guess we can review the code where the "replace" function is being called. Check if the arguments passed to the function are correct and if they fall within the valid range for the string. Additionally, make sure that you have included the necessary headers, such as `<string>`, for using the "std::basic_string" class.

**NOTE**: It is relevant to note that this is happening in the second time step, not in the first one, which converges and *a priori* is finished properly. Maybe is not properly "close" and thats why is failing.

**Comment by loumalouomega** [comment]
FYI @pooyan-dadvand and Sandip Kumar (TODO: Mention him once I know its username in Github)

**Comment by philbucher** [comment]
Can you also try with file-based serialization (aka file comm)

**Comment by loumalouomega** [comment]
Okay @sandy1909 fixed this, he can explain details. i will close this

**Comment by philbucher** [comment]
So in the end was the problem in CoSimIO or elsewhere?

**Comment by loumalouomega** [comment]
> So in the end was the problem in CoSimIO or elsewhere?

I don't know, @sandy1909 fixed it, I don't know the details. I am a middle man
