### ISSUE TITLE
Bug in code location

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/CoSimIO#350]
I found out that the CodeLocation implementation fails in windows with an exception and causes exception within another exception situation which won't show the result.

The problem is in using [return fs::canonical(fs::path(GetFileName())).lexically_relative(fs::absolute(".")).string();](https://github.com/KratosMultiphysics/CoSimIO/blob/a5abb50a6910d6eb2af5788307c8d9949cd884e8/co_sim_io/sources/code_location.cpp#L24) 

And replacing it with the manual implementation in [Kratos](https://github.com/KratosMultiphysics/Kratos/blob/c1d9b2e30b557612aa379acfa2e16298523731a8/kratos/sources/code_location.cpp#L46) just solved the problem.

@philbucher It would be great if we you could create a release with this fix.

**Comment by philbucher** [comment]
I will look into it

Too bad, I was quite happy with the existing solution :/

Can you please post the error?

**Comment by pooyan-dadvand** [comment]
The problem is that there is no error message!

@philbucher Would you please fix it and add it to the kratos?
