### ISSUE TITLE
Build script has debug as the build type

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/CoSimIO#359]
The [scripts/build.sh](https://github.com/KratosMultiphysics/CoSimIO/blob/2093dfa4dc429f47c79c27beba02a7becca65013/scripts/build.sh#L18) is setting build type to debug in the release source. I would suggest to change it to release.

**Comment by loumalouomega** [comment]
@philbucher I would agree with this

**Comment by loumalouomega** [comment]
@philbucher I can confirm this happens in Windows, can you make me developer so I can do a PR without doing a fork?

**Comment by philbucher** [comment]
> @philbucher I can confirm this happens in Windows, can you make me developer so I can do a PR without doing a fork?

done, thx!

**Comment by philbucher** [comment]
(added you to the CoSimTeam, I think it makes sense for you)
