### ISSUE TITLE
build_c.sh compiles and installs in debug folder in windows

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/CoSimIO#360]
Even setting the build type to release it adds the debug info and installs in debug folder in windows

**Comment by loumalouomega** [comment]
Okay

**Comment by philbucher** [comment]
this is weird, if nothing is specified then it should be release
https://github.com/KratosMultiphysics/CoSimIO/blob/2093dfa4dc429f47c79c27beba02a7becca65013/CMakeLists.txt#L29-L35

@pooyan-dadvand how did you specify the build type?

**Comment by pooyan-dadvand** [comment]
By not defining anything first, but then by specifying both variables without success.
In configuration it says release:
![image](https://github.com/KratosMultiphysics/CoSimIO/assets/8911479/657f6b23-65c3-4d17-bd52-78d1b186dd87)

But when compiling the build root goes in debug:

![image](https://github.com/KratosMultiphysics/CoSimIO/assets/8911479/18d0fa0d-970b-430f-9230-fa76cbb2216e)

**Comment by loumalouomega** [comment]
We can close this
